
var map,zoom,center,require,dojo,scalebar,checkNull,content;require(["esri/map","esri/dijit/Scalebar","esri/dijit/Popup","esri/dijit/BasemapGallery","dijit/layout/BorderContainer","dijit/layout/ContentPane","dijit/TitlePane","esri/layers/FeatureLayer","esri/layers/ArcGISDynamicMapServiceLayer","esri/layers/ArcGISTiledMapServiceLayer","esri/layers/ImageParameters","esri/symbols/SimpleFillSymbol","esri/symbols/SimpleLineSymbol","esri/Color","esri/tasks/IdentifyTask","esri/tasks/IdentifyParameters","esri/InfoTemplate","esri/dijit/Geocoder","dojo/parser","dojo/domReady!"],function(Map,Scalebar,Popup,BasemapGallery,BorderContainer,ContentPane,TitlePane,FeatureLayer,ArcGISDynamicMapServiceLayer,ArcGISTiledMapServiceLayer,ImageParameters,SimpleFillSymbol,SimpleLineSymbol,Color,IdentifyTask,IdentifyParameters,InfoTemplate,Geocoder,parser){parser.parse();var popup=new Popup({fillSymbol:new SimpleFillSymbol(SimpleFillSymbol.STYLE_SOLID,new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID,new Color([255,0,0]),2),new Color([255,255,0,0.25]))},dojo.create("div"));center=[-79.2,39.5];zoom=10;map=new Map("mapDiv",{basemap:"streets",center:center,zoom:zoom,infoWindow:popup});scalebar=new Scalebar({map:map,attachTo:"bottom-right",scalebarStyle:"line",scalebarUnit:"english"});checkNull=function(value,key,data){function determineVal(val,strKey,addBreak){if(val=="Null"){content="";}else{if(addBreak){if(strKey=="SDAT Link: <a href=\""){val+="\" target=\"_blank\">LINK</a>";}
val+="<br />";}
content=strKey+val;}}
switch(key){case"SUBDIVSN":determineVal(value,"Subdivision: ",true);break;case"PLAT":determineVal(value,"Plat: ",true);break;case"BLOCK":determineVal(value,"Block: ",true);break;case"PLTLIBER":determineVal(value,"<hr><span class=\"sectionhead\">Plat Reference</span><br />Liber: ",true);break;case"PLTFOLIO":determineVal(value,"Folio: ",true);break;case"OWNNAME2":determineVal(value," ",false);break;case"SDAT_URL":determineVal(value,"SDAT Link: <a href=\"",true);break;}
return content;}
map.on("click",executeIdentifyTask);var flzTemplate=new esri.InfoTemplate("","<span class=\"sectionhead\">Layer: FEMA Flood Hazard Zones </span><br /><br /><hr>Flood Zone: ${FLD_ZONE} <br/>");var parcelTemplate=new esri.InfoTemplate("","<span class=\"sectionhead\">Layer: Parcels</span><br /><br /><hr>Address: ${ADDRESS} <br />"
+"City: ${CITY} <br /> Owner: ${OWNNAME1} ${OWNNAME2:checkNull} <br /> Tax Id: ${ACCTID} <br /><hr><span class=\"sectionhead\">Deed Reference</span><br />"
+"Liber: ${DR1LIBER} <br /> Folio: ${DR1FOLIO} <br /><hr> ${SUBDIVSN:checkNull} ${PLAT:checkNull} ${BLOCK:checkNull} Grid: ${GRID} <br />"
+"Map: ${MAP} <br /> Parcel: ${PARCEL} <br /> Lot: ${LOT} <br /> Area: ${ACRES} Acres <br />"
+"${PLTLIBER:checkNull} ${PLTFOLIO:checkNull} <hr>"
+"Year Built: ${YRBLT_CAMA} <br /> ${SDAT_URL:checkNull}");var addrTemplate=new esri.InfoTemplate("Address Info","<span class=\"sectionhead\">Layer: Address Points</span><br /><br /><hr>Address: ${ADDRESS} <br /><br /> City: ${CITY} <br /> Zip: ${ZIP_CODE} <br /> ESN: ${ESN} <br /> Community: ${COMMUNITY} <br /> Map: ${MAP} <br /> Parcel: ${PARCEL} <br />"
+"Lot: ${LOT} <br /> Tract: ${TRACT} <br /> LU: ${LU} <br /> Key date: ${KEYDATE} <br /> Rental: ${RENTAL} <br />"
+"Rental Co.: ${RENTAL_CO} <br /> Tax Account: ${TAX_ACCOUNT_ID} <br /> Owner: ${OWNER_FIRST_NAME} ${OWNER_LAST_NAME} <br />");var streetTemplate=new esri.InfoTemplate("","<span class=\"sectionhead\">Layer: Street Centerlines</span><br /><br /><hr>Name: ${STREET_ALL} <br />"
+"Maintenance: ${MAINTENANCE} <br /> Length: ${SHAPE_Length:NumberFormat} feet <br />");fpFEMA_task=new IdentifyTask("http://gis.garrettcounty.org:6080/arcgis/rest/services/FEMA/Flood_Hazard/MapServer/");var imageParameters=new ImageParameters();imageParameters.layerIds=[0,1,2,3];imageParameters.layerOption=ImageParameters.LAYER_OPTION_SHOW;var layerFEMA=new ArcGISDynamicMapServiceLayer("http://gis.garrettcounty.org:6080/arcgis/rest/services/FEMA/Flood_Hazard/MapServer/",{"imageParameters":imageParameters,opacity:0.75});map.addLayer(layerFEMA);var basemapGallery=new BasemapGallery({showArcGISBasemaps:true,map:map},"basemapGallery");mdImagelayer=new esri.layers.ArcGISTiledMapServiceLayer("http://geodata.md.gov/imap/rest/services/Imagery/MD_SixInchImagery/MapServer");mdImageBasemap=new esri.dijit.Basemap({layers:[mdImagelayer],title:"MD Imagery",thumbnailUrl:"http://gis.garrettcounty.org/arcgis/images/image_v2.png"});basemapGallery.add(mdImageBasemap);basemapGallery.startup();basemapGallery.on("error",function(msg){console.log("basemap gallery error:  ",msg);});function executeIdentifyTask(evt){identifyParams=new IdentifyParameters();identifyParams.tolerance=3;identifyParams.returnGeometry=true;identifyParams.layerOption=IdentifyParameters.LAYER_OPTION_VISIBLE;identifyParams.width=map.width;identifyParams.height=map.height;identifyParams.geometry=evt.mapPoint;identifyParams.mapExtent=map.extent;identifyParams.tolerance=3;identifyParams.SpatialReference=102100;identifyParams.layerIds=[0,1,2,3];var deferred=fpFEMA_task.execute(identifyParams);deferred.addCallback(function(response){return dojo.map(response,function(result){var feature=result.feature;if(result.layerName==='Flood Hazard Areas'){console.log("Flood Zone: "+feature.attributes.FLD_ZONE);feature.setInfoTemplate(flzTemplate);}
else if(result.layerName==='addresspoints'){feature.setInfoTemplate(addrTemplate);}
else if(result.layerName==='Garrett.DBO.TaxParcel'){feature.setInfoTemplate(parcelTemplate);}
else if(result.layerName==='centerlines'){feature.setInfoTemplate(streetTemplate);}
return feature;},function(error){console.log("Error: "+error);});});map.infoWindow.setFeatures([deferred]);map.infoWindow.show(evt.mapPoint);};geocoder=new Geocoder({map:map},"geosearch");geocoder.startup();});